import {
  collection,
  doc,
  getDoc,
  getDocs,
  limit,
  onSnapshot,
  query,
  runTransaction,
  setDoc,
  updateDoc,
  where,
} from "firebase/firestore";
import { PLAYERS } from "../data/players";
import type { Era, Player } from "../data/players";
import { ERAS, SLOTS, rosterStrength, targetsFor, teamsForEra, teamsPresentInEra } from "../engine/draft";
import type { FilledSlots } from "../engine/draft";
import { generateAllTimeBoard, generateDailyBoard, hasPerfectMatching, tileCanFillSlot, tilePlayers } from "../engine/daily";
import type { DailyTile } from "../engine/daily";
import { playGame } from "../engine/season";
import { simulateDriveSequence } from "../engine/driveSim";
import type { DriveEvent } from "../engine/driveSim";
import { getDb, getUid } from "./firebase";

export type MatchTile = DailyTile;

export interface MatchResult {
  winnerUid: string | null; // null on a tie
  hostStrength: number;
  guestStrength: number;
  hostScore: number;
  guestScore: number;
  // Computed once, here, by whichever pick finalizes the match — never
  // regenerated per-client — so both players watch the identical
  // drive-by-drive narration rather than each fabricating their own.
  driveSequence: DriveEvent[];
  // Wall-clock time (Date.now(), from whichever client's pick finalized
  // the match) both players' local playback is timed relative to, so
  // the animation is in sync rather than starting whenever each
  // player's own screen happens to render "done".
  revealStartedAt: number;
}

export interface SwapTile {
  round: number;
  tile: MatchTile;
}

export interface MatchDoc {
  status: "waiting" | "active" | "done";
  createdAt: number;
  hostUid: string;
  hostName: string;
  guestUid: string | null;
  guestName: string | null;
  // When true, hostBoard and guestBoard are the identical sequence — the
  // original design, both players facing the same matchup each round.
  // When false, each player gets their own independently generated
  // board, so the round-by-round matchups genuinely differ between them
  // (still each individually generated by generateDailyBoard/
  // generateAllTimeBoard, so each is still guaranteed solvable on its
  // own). guestBoard is null until a guest actually exists — for
  // sameBoard rooms it's set to a copy of hostBoard the moment the
  // second player is known (join or rematch-creation); for different-
  // board rooms it's generated fresh at that same moment, since it has
  // no reason to exist before someone's actually going to play it.
  sameBoard: boolean;
  hostBoard: MatchTile[];
  guestBoard: MatchTile[] | null;
  rosters: Record<string, Record<string, number>>; // uid -> slot key -> player id
  // Each player's one personal, private reroll: which round it replaced
  // and with what, if they've used it. Only ever holds at most one entry
  // per uid — replacing the current round's tile for that player alone;
  // it has no effect on the other player's own board either way.
  swaps: Record<string, SwapTile>;
  readyUids: string[];
  result: MatchResult | null;
  quickMatch: boolean;
  // When true, every tile is a whole franchise's all-time roster (every
  // era it's ever fielded a player in) instead of one specific decade —
  // naturally far deeper per tile, so this is the escape hatch for
  // still running into a thin 1-2 player tile occasionally even with
  // generateDailyBoard's own depth guarantee.
  allTimeMode: boolean;
  // Mutual "run it back": uids who've asked for a rematch with this same
  // opponent. Once both have, whichever vote got there second creates a
  // fresh room (both players pre-filled, so it skips straight to
  // active) and records its code here — both clients watch this field
  // and navigate themselves into that room once it appears.
  rematchVotes: string[];
  rematchCode: string | null;
}

const CODE_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"; // no 0/O/1/I/L

function randomCode(len = 5): string {
  let s = "";
  for (let i = 0; i < len; i++) s += CODE_ALPHABET[Math.floor(Math.random() * CODE_ALPHABET.length)];
  return s;
}

function generateBoard(allTimeMode: boolean): MatchTile[] {
  return allTimeMode ? generateAllTimeBoard() : generateDailyBoard(`${Date.now()}:${Math.random()}`);
}

/** The board a given player actually drafts from — hostBoard for the
 *  host, guestBoard for the guest (falling back to hostBoard if
 *  guestBoard somehow isn't set yet, which shouldn't happen once a
 *  guest exists at all — every path that sets guestUid also sets
 *  guestBoard in the same write). */
export function boardFor(match: Pick<MatchDoc, "hostUid" | "hostBoard" | "guestBoard">, uid: string): MatchTile[] {
  return uid === match.hostUid ? match.hostBoard : (match.guestBoard ?? match.hostBoard);
}

/** Creates a new room and returns its join code. Retries on the
 *  astronomically unlikely chance of a code collision. `quickMatch` tags
 *  the room as discoverable by joinQuickMatch below — an invite-link room
 *  is otherwise identical, just never advertised. `allTimeMode` swaps in
 *  generateAllTimeBoard (whole-franchise tiles) instead of the daily
 *  challenge's era-restricted generator. `sameBoard` (default true)
 *  decides whether the eventual guest faces the identical sequence as
 *  the host or their own independently generated one — see MatchDoc. */
export async function createRoom(
  name: string,
  quickMatch = false,
  allTimeMode = false,
  sameBoard = true
): Promise<string> {
  const uid = await getUid();
  const db = getDb();
  for (let attempt = 0; attempt < 5; attempt++) {
    const code = randomCode();
    const ref = doc(db, "matches", code);
    const existing = await getDoc(ref);
    if (existing.exists()) continue;
    const hostBoard = generateBoard(allTimeMode);
    const match: MatchDoc = {
      status: "waiting",
      createdAt: Date.now(),
      hostUid: uid,
      hostName: name || "Anonymous",
      guestUid: null,
      guestName: null,
      sameBoard,
      hostBoard,
      guestBoard: null, // set once a guest actually exists — see joinRoom/findAndClaimQuickMatch
      rosters: { [uid]: {} },
      swaps: {},
      readyUids: [],
      result: null,
      quickMatch,
      allTimeMode,
      rematchVotes: [],
      rematchCode: null,
    };
    await setDoc(ref, match);
    return code;
  }
  throw new Error("Couldn't create a room — try again.");
}

/** Joins an existing waiting room as the guest. */
export async function joinRoom(code: string, name: string): Promise<void> {
  const uid = await getUid();
  const db = getDb();
  const ref = doc(db, "matches", code.toUpperCase());
  await runTransaction(db, async (tx) => {
    const snap = await tx.get(ref);
    if (!snap.exists()) throw new Error("That room code doesn't exist.");
    const match = snap.data() as MatchDoc;
    if (match.hostUid === uid) return; // already the host, nothing to do
    if (match.guestUid === uid) return; // already joined, e.g. a refresh
    if (match.status !== "waiting" || match.guestUid) throw new Error("That room's already full.");
    tx.update(ref, {
      guestUid: uid,
      guestName: name || "Anonymous",
      status: "active",
      guestBoard: match.sameBoard ? match.hostBoard : generateBoard(match.allTimeMode),
      [`rosters.${uid}`]: {},
    });
  });
}

const QUICK_MATCH_STALE_MS = 5 * 60 * 1000;

/** Searches for an already-waiting quick-match room (same allTimeMode,
 *  not stale, not my own) and atomically claims the oldest one it can —
 *  the transaction re-checks the document fresh, so if two searchers
 *  race for the *same* candidate, only one wins and the other falls
 *  through to try the next. Returns null if nothing was available (or
 *  every attempt lost its race), not an error — this is the expected
 *  "nobody's waiting right now" case, not a failure.
 *
 *  `onlyIfWinningTiebreak`, when set, further restricts candidates to
 *  ones whose hostUid sorts before mine — see joinQuickMatch for why
 *  that matters for its second search specifically. */
async function findAndClaimQuickMatch(
  db: ReturnType<typeof getDb>,
  uid: string,
  name: string,
  allTimeMode: boolean,
  sameBoard: boolean,
  onlyIfWinningTiebreak = false
): Promise<string | null> {
  // No orderBy here (deliberately — combining it with the where() below
  // would need a composite index, a manual Firestore console step this
  // project otherwise avoids requiring), so this can return an arbitrary
  // 20 of however many quickMatch:true documents exist — including any
  // stale orphans that piled up over time, which never get deleted
  // (the security rules don't allow it). A too-small limit here was a
  // real, confirmed bug: once enough orphans exist, an arbitrary 20 of
  // them can crowd out the one fresh, genuinely-waiting room a search
  // should have found. 300 is comfortably more than this app should
  // ever see stay *simultaneously non-stale* at its actual scale.
  const q = query(collection(db, "matches"), where("quickMatch", "==", true), limit(300));
  const snap = await getDocs(q);
  const now = Date.now();
  const candidates = snap.docs
    .map((d) => ({ ref: d.ref, data: d.data() as MatchDoc }))
    .filter(
      (c) =>
        c.data.status === "waiting" &&
        c.data.hostUid !== uid &&
        !!c.data.allTimeMode === allTimeMode &&
        !!c.data.sameBoard === sameBoard &&
        now - c.data.createdAt < QUICK_MATCH_STALE_MS &&
        (!onlyIfWinningTiebreak || uid > c.data.hostUid)
    )
    .sort((a, b) => a.data.createdAt - b.data.createdAt);

  for (const candidate of candidates) {
    try {
      await runTransaction(db, async (tx) => {
        const fresh = await tx.get(candidate.ref);
        if (!fresh.exists()) throw new Error("gone");
        const m = fresh.data() as MatchDoc;
        if (m.status !== "waiting" || m.guestUid) throw new Error("taken");
        tx.update(candidate.ref, {
          guestUid: uid,
          guestName: name || "Anonymous",
          status: "active",
          guestBoard: m.sameBoard ? m.hostBoard : generateBoard(m.allTimeMode),
          [`rosters.${uid}`]: {},
        });
      });
      return candidate.ref.id;
    } catch {
      continue; // someone else grabbed it (or it's gone) — try the next one
    }
  }
  return null;
}

/** Finds a random opponent: joins someone else's already-waiting
 *  quick-match room if one exists, or creates one and returns its code
 *  so the caller can wait on it exactly like an invite-link room (the
 *  same subscribeRoom/waiting-room flow applies either way — the only
 *  difference is how the code was obtained). Reuses the plain matches
 *  collection (tagged `quickMatch: true`) rather than a separate queue
 *  collection, so it needs no security rules beyond what
 *  createRoom/joinRoom already require.
 *
 *  The initial search-then-maybe-create isn't atomic across two
 *  different players — if both search at nearly the same moment, before
 *  either has created anything yet, each one's search can come back
 *  empty and each independently creates its own room, so neither ever
 *  finds the other (this was a real, reported bug). A second search
 *  shortly after creating a room catches the overwhelming majority of
 *  real cases — by then the other player's create has almost always
 *  propagated — and switches to joining theirs instead of leaving two
 *  rooms stranded.
 *
 *  That second search has its own race, though: if *both* players reach
 *  it at nearly the same moment (which, having just gone through the
 *  identical steps in lockstep, is common), each one's search finds the
 *  *other's* room and independently claims it in its own transaction —
 *  and since those are two different documents, both transactions
 *  succeed. Each player ends up the guest of the other's room instead
 *  of sharing one (confirmed live: this reproduced in 3 of 8 trials
 *  before the fix below). Breaking the symmetry fixes it: the second
 *  search only claims a candidate whose hostUid sorts before mine, so
 *  of any two players racing each other, only the one with the "larger"
 *  uid actively claims — the other just keeps waiting on its own room,
 *  the same as it would if no race were happening at all. */
export async function joinQuickMatch(name: string, allTimeMode = false, sameBoard = true): Promise<string> {
  const uid = await getUid();
  const db = getDb();

  const found = await findAndClaimQuickMatch(db, uid, name, allTimeMode, sameBoard);
  if (found) return found;

  const myCode = await createRoom(name, true, allTimeMode, sameBoard);
  await new Promise((resolve) => setTimeout(resolve, 400));

  const foundAfter = await findAndClaimQuickMatch(db, uid, name, allTimeMode, sameBoard, true);
  if (foundAfter) {
    updateDoc(doc(db, "matches", myCode), { quickMatch: false }).catch(() => {
      /* best-effort cleanup — an extra untagged orphan room isn't harmful */
    });
    return foundAfter;
  }
  return myCode;
}

/** Live-subscribes to a room's state. Returns an unsubscribe function. */
export function subscribeRoom(code: string, cb: (match: MatchDoc | null) => void): () => void {
  const db = getDb();
  const ref = doc(db, "matches", code.toUpperCase());
  return onSnapshot(ref, (snap) => cb(snap.exists() ? (snap.data() as MatchDoc) : null));
}

export function rosterFromIds(roster: Record<string, number>): FilledSlots {
  const filled: FilledSlots = {};
  for (const slot of SLOTS) {
    const pid = roster[slot.key];
    if (pid == null) continue;
    const p = PLAYERS.find((pl) => pl.id === pid);
    if (p) filled[slot.key] = p;
  }
  return filled;
}

/** The tile a given player actually faces at a given round — their own
 *  board (see boardFor — identical to their opponent's in sameBoard
 *  rooms, independently generated otherwise), unless they've spent
 *  their personal skip on this exact round, in which case it's their
 *  private replacement. */
export function effectiveTile(
  match: Pick<MatchDoc, "hostUid" | "hostBoard" | "guestBoard" | "swaps">,
  uid: string,
  round: number
): MatchTile {
  const swap = match.swaps[uid];
  return swap && swap.round === round ? swap.tile : boardFor(match, uid)[round];
}

function randomTeamEraExcluding(exclude: Set<string>): { era: Era; team: string } | null {
  // Prefer an era that still has an unused deep (3+ player) team at all,
  // so a skip's replacement doesn't land you on a 1-player team just
  // because the era it happened to roll first was already tapped out —
  // same fix as generateDailyBoard's own era selection.
  const erasWithDeep = ERAS.filter((era) => teamsForEra(era, {}).some((t) => !exclude.has(`${era}|${t}`)));
  const eraPool = erasWithDeep.length ? erasWithDeep : ERAS;
  for (let attempt = 0; attempt < 60; attempt++) {
    const era = eraPool[Math.floor(Math.random() * eraPool.length)];
    const deep = teamsForEra(era, {}).filter((t) => !exclude.has(`${era}|${t}`));
    const any = teamsPresentInEra(era).filter((t) => !exclude.has(`${era}|${t}`));
    const pool = deep.length ? deep : any;
    if (!pool.length) continue;
    const team = pool[Math.floor(Math.random() * pool.length)];
    return { era, team };
  }
  return null;
}

function randomAllTimeTeamExcluding(exclude: Set<string>): string | null {
  const allTeams = [...new Set(PLAYERS.map((p) => p.team))].filter((t) => !exclude.has(t));
  if (!allTeams.length) return null;
  return allTeams[Math.floor(Math.random() * allTeams.length)];
}

/** Claims your one personal reroll: swaps the tile for whichever round
 *  you're currently on (derived from how many slots you've already
 *  filled) into a new random team/era — for you only, keeping the rest
 *  of the fixed sequence intact for your opponent. Only tries candidates
 *  that keep your remaining rounds solvable (same guarantee the original
 *  board was built with), and only tries team/era pairs you don't
 *  already face elsewhere in your own sequence. */
export async function useSkip(code: string): Promise<void> {
  const uid = await getUid();
  const db = getDb();
  const ref = doc(db, "matches", code.toUpperCase());
  await runTransaction(db, async (tx) => {
    const snap = await tx.get(ref);
    if (!snap.exists()) throw new Error("This match no longer exists.");
    const match = snap.data() as MatchDoc;
    if (match.status !== "active") throw new Error("This match isn't active.");
    if (match.swaps[uid]) throw new Error("You've already used your skip.");

    const myRoster = match.rosters[uid] ?? {};
    const myBoard = boardFor(match, uid);
    const round = Object.keys(myRoster).length;
    if (round >= myBoard.length) throw new Error("Nothing left to skip.");

    const futureTiles = myBoard.slice(round + 1);
    const remainingSlotKeys = SLOTS.filter((s) => myRoster[s.key] == null).map((s) => s.key);

    let replacement: MatchTile | null = null;
    if (match.allTimeMode) {
      const exclude = new Set(myBoard.map((t) => t.team));
      for (let attempt = 0; attempt < 40; attempt++) {
        const team = randomAllTimeTeamExcluding(exclude);
        if (!team) break;
        const tile: MatchTile = { key: `swap-${uid}-${round}-${attempt}`, era: null, team };
        if (hasPerfectMatching([tile, ...futureTiles], remainingSlotKeys)) {
          replacement = tile;
          break;
        }
        exclude.add(team); // don't keep retrying the same rejected team
      }
    } else {
      const exclude = new Set(myBoard.map((t) => `${t.era}|${t.team}`));
      for (let attempt = 0; attempt < 40; attempt++) {
        const candidate = randomTeamEraExcluding(exclude);
        if (!candidate) break;
        const tile: MatchTile = { key: `swap-${uid}-${round}-${attempt}`, era: candidate.era, team: candidate.team };
        if (hasPerfectMatching([tile, ...futureTiles], remainingSlotKeys)) {
          replacement = tile;
          break;
        }
        exclude.add(`${candidate.era}|${candidate.team}`); // don't keep retrying the same rejected pair
      }
    }
    if (!replacement) throw new Error("Couldn't find a fair swap right now — try again in a moment.");

    tx.update(ref, { [`swaps.${uid}`]: { round, tile: replacement } });
  });
}

/** Drafts one player into one of your open slots, for whichever round
 *  you're currently on. Rejects (defensively — this isn't meant to be a
 *  hardened anti-cheat boundary, just enough to keep a stray bug or a
 *  tampered request from corrupting a match) a player who doesn't
 *  actually belong to your current tile, a position that doesn't fit the
 *  slot, or a slot you've already filled. Also rejects a pick that would
 *  strand a later slot of yours — checked against your own remaining
 *  rounds and open slots only, entirely independent of your opponent's
 *  choices, since nothing here is shared or contested. Once both players
 *  have filled every slot, this same transaction simulates the one
 *  head-to-head game and marks the match done — whichever of the two
 *  picks happens to complete the second roster is the sole writer for
 *  that transition, so the result is never computed twice. */
export async function draftPick(code: string, slotKey: string, playerId: number): Promise<void> {
  const uid = await getUid();
  const db = getDb();
  const ref = doc(db, "matches", code.toUpperCase());
  await runTransaction(db, async (tx) => {
    const snap = await tx.get(ref);
    if (!snap.exists()) throw new Error("This match no longer exists.");
    const match = snap.data() as MatchDoc;
    if (match.status !== "active") throw new Error("This match isn't active.");

    const myRoster = match.rosters[uid] ?? {};
    if (myRoster[slotKey] != null) throw new Error("You've already filled that slot.");
    const myBoard = boardFor(match, uid);
    const round = Object.keys(myRoster).length;
    if (round >= myBoard.length) throw new Error("Your roster is already full.");

    const tile = effectiveTile(match, uid, round);
    const player = PLAYERS.find((p) => p.id === playerId);
    if (!player || player.team !== tile.team || (tile.era !== null && player.era !== tile.era)) {
      throw new Error("That player isn't on this round's board.");
    }
    if (!tileCanFillSlot(tile, slotKey)) throw new Error("That player doesn't fit that slot.");

    const nextRoster = { ...myRoster, [slotKey]: playerId };
    const futureTiles = myBoard.slice(round + 1);
    const remainingSlotKeys = SLOTS.filter((s) => nextRoster[s.key] == null).map((s) => s.key);
    if (!hasPerfectMatching(futureTiles, remainingSlotKeys)) {
      throw new Error("That pick would leave a later slot with nobody left to fill it.");
    }

    const update: Record<string, unknown> = { [`rosters.${uid}`]: nextRoster };

    const amReady = Object.keys(nextRoster).length >= SLOTS.length;
    const readyUids = amReady && !match.readyUids.includes(uid) ? [...match.readyUids, uid] : match.readyUids;
    if (amReady && readyUids !== match.readyUids) update.readyUids = readyUids;

    if (readyUids.length >= 2 && match.hostUid && match.guestUid) {
      const hostRoster = match.hostUid === uid ? nextRoster : (match.rosters[match.hostUid] ?? {});
      const guestRoster = match.guestUid === uid ? nextRoster : (match.rosters[match.guestUid] ?? {});
      const hostStrength = rosterStrength(rosterFromIds(hostRoster));
      const guestStrength = rosterStrength(rosterFromIds(guestRoster));
      // playGame always produces a nonzero margin, so there's no tie to
      // handle — win is always from the host's (first-argument) perspective.
      const game = playGame(hostStrength, guestStrength, null);
      const result: MatchResult = {
        winnerUid: game.win ? match.hostUid : match.guestUid,
        hostStrength,
        guestStrength,
        hostScore: game.mp,
        guestScore: game.op,
        driveSequence: simulateDriveSequence(game.mp, game.op),
        revealStartedAt: Date.now(),
      };
      update.status = "done";
      update.result = result;
    }

    tx.update(ref, update);
  });
}

/** Creates a fresh room with both players already known — skips the
 *  usual solo "waiting" stage entirely, since a rematch has no one left
 *  to invite. The create is written with status 'waiting' first (the
 *  only shape the security rules' create clause allows) and then flipped
 *  to 'active' in a second write, which the update clause allows for
 *  whoever just created it (they're its hostUid). */
async function createRematchRoom(
  myUid: string,
  myName: string,
  otherUid: string,
  otherName: string,
  allTimeMode: boolean,
  sameBoard: boolean
): Promise<string> {
  const db = getDb();
  for (let attempt = 0; attempt < 5; attempt++) {
    const code = randomCode();
    const ref = doc(db, "matches", code);
    const existing = await getDoc(ref);
    if (existing.exists()) continue;
    const hostBoard = generateBoard(allTimeMode);
    const match: MatchDoc = {
      status: "waiting",
      createdAt: Date.now(),
      hostUid: myUid,
      hostName: myName || "Anonymous",
      guestUid: otherUid,
      guestName: otherName || "Anonymous",
      sameBoard,
      hostBoard,
      guestBoard: sameBoard ? hostBoard : generateBoard(allTimeMode),
      rosters: { [myUid]: {}, [otherUid]: {} },
      swaps: {},
      readyUids: [],
      result: null,
      quickMatch: false,
      allTimeMode,
      rematchVotes: [],
      rematchCode: null,
    };
    await setDoc(ref, match);
    await updateDoc(ref, { status: "active" });
    return code;
  }
  throw new Error("Couldn't set up a rematch — try again.");
}

/** Votes to run it back with the same opponent. Once both players have
 *  voted, a fresh room is created automatically (see createRematchRoom)
 *  and its code is recorded on this match doc — both clients watch
 *  rematchCode via their existing subscribeRoom listener and navigate
 *  themselves into it, so nobody has to share a new code manually.
 *
 *  Whether *this* call is the one that creates the room is decided
 *  entirely from inside the vote transaction itself, not from a
 *  separate read afterward — Firestore serializes conflicting
 *  transactions on the same document, so if both players vote at
 *  nearly the same moment, one of the two transactions is guaranteed to
 *  be retried against the other's already-committed vote and see the
 *  count reach two from within itself. Deciding this from a follow-up
 *  read instead (the earlier version of this function) had a real race:
 *  both clients' post-vote reads could each land in the narrow window
 *  where they only saw their own vote, so neither ever created the
 *  room and both got stuck waiting on each other forever. */
export async function voteRematch(code: string, name: string): Promise<void> {
  const uid = await getUid();
  const db = getDb();
  const ref = doc(db, "matches", code.toUpperCase());

  let iShouldCreate = false;
  let otherUid = "";
  let otherName = "";
  let allTimeMode = false;
  let sameBoard = true;

  await runTransaction(db, async (tx) => {
    const snap = await tx.get(ref);
    if (!snap.exists()) throw new Error("This match no longer exists.");
    const match = snap.data() as MatchDoc;
    if (match.status !== "done") throw new Error("This match isn't finished yet.");
    if (match.rematchVotes.includes(uid)) return;

    const votes = [...match.rematchVotes, uid];
    tx.update(ref, { rematchVotes: votes });

    if (votes.length >= 2 && !match.rematchCode && match.hostUid && match.guestUid) {
      iShouldCreate = true;
      otherUid = match.hostUid === uid ? match.guestUid : match.hostUid;
      otherName = (match.hostUid === uid ? match.guestName : match.hostName) ?? "";
      allTimeMode = match.allTimeMode;
      sameBoard = match.sameBoard;
    }
  });

  if (!iShouldCreate) return;

  const newCode = await createRematchRoom(uid, name, otherUid, otherName, allTimeMode, sameBoard);
  await runTransaction(db, async (tx) => {
    const snap = await tx.get(ref);
    if (!snap.exists()) return;
    const m = snap.data() as MatchDoc;
    if (m.rematchCode) return; // shouldn't happen now, but stay defensive
    tx.update(ref, { rematchCode: newCode });
  });
}

/** Every slot this player could actually be drafted into right now, for
 *  this round: a slot their position fits, that's still open, and that
 *  wouldn't strand one of your own later rounds if you picked it (see
 *  draftPick's identical guard — this is the read-only, client-side
 *  mirror of it, so the UI can hide a choice before it'd be rejected
 *  rather than show it disabled). Only your own remaining rounds and
 *  open slots matter here — nothing about this is shared or contested. */
export function feasibleTargetsThisRound(
  board: MatchTile[],
  round: number,
  player: Player,
  myFilled: FilledSlots
): string[] {
  const futureTiles = board.slice(round + 1);
  return targetsFor(player, myFilled).filter((slotKey) => {
    const remainingSlotKeys = SLOTS.filter((s) => s.key !== slotKey && !myFilled[s.key]).map((s) => s.key);
    return hasPerfectMatching(futureTiles, remainingSlotKeys);
  });
}

/** Every player on this round's tile worth showing at all — at least one
 *  feasible slot per feasibleTargetsThisRound above. Mirrors the daily
 *  challenge's "hide it, don't show it disabled" rule (see DailyDraft.tsx)
 *  rather than rendering a locked, unusable card. */
export function draftableThisRound(board: MatchTile[], round: number, tile: MatchTile, myFilled: FilledSlots): Player[] {
  return tilePlayers(tile).filter((p) => feasibleTargetsThisRound(board, round, p, myFilled).length > 0);
}
